# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Open Source Paradise
tagline:          'A Jekyll theme'
description:      'descripción'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
